version: "3"
services:
    front:
        build: front/project-sharing-page

    userapi:
        build: userapi
        links:
            - userdb
        depends_on:
            - userdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
    
    projectapi:
        build: projectapi
        links:
            - projectdb
        depends_on:
            - projectdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
    
    chatapi:
        build: chatapi
        links:
            - chatdb
        depends_on:
            - chatdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
    
    caddy:
        image: caddy
        volumes:
            - "./Caddyfile:/etc/caddy/Caddyfile"
        links:
            - userapi
            - front
        environment: 
            TZ: "UTC"
            HOSTNAME: "localhost"
        depends_on:
            - userapi
            - front
        ports:
            - 80:80
            - 443:443

    userdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "userpgdata:/var/lib/postgresql/data"
    
    projectdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "projectpgdata:/var/lib/postgresql/data"
    
    chatdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "chatpgdata:/var/lib/postgresql/data"

        
volumes: 
    userpgdata:
        driver: "local"
    projectpgdata:
        driver: "local"
    chatpgdata:
        driver: "local"
