version: "3"
services:
    front:
        build: front/project-sharing-page

    userapi:
        build: 
            context: userapi
            dockerfile: Dockerfile_dev
        links:
            - userdb
        depends_on:
            - userdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "True"
        volumes:
            - ./userapi:/code
    
    projectapi:
        build:
            context: projectapi
            dockerfile: Dockerfile_dev
        links:
            - projectdb
        depends_on:
            - projectdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "True"
        volumes: 
            - ./projectapi:/code
    
    chatapi:
        build:
            context: chatapi
            dockerfile: Dockerfile_dev
        links:
            - chatdb
        depends_on:
            - chatdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "True"
        volumes: 
            - ./chatapi:/code

    recommendapi:
        build: recommendapi
        links:
            - recommenddb
        depends_on:
            - recommenddb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
        volumes: 
            - ./recommendapi:/code
    
    caddy:
        image: caddy
        volumes:
            - "./CaddyfileDev:/etc/caddy/Caddyfile"
        links:
            - userapi
            - front
        environment: 
            TZ: "UTC"
            HOSTNAME: "localhost"
        depends_on:
            - userapi
            - front
        ports:
            - 8080:80
            - 8081:443

    userdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "userpgdata:/var/lib/postgresql/data"
        ports:
          - 5432:5432  # Debug
    
    projectdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "projectpgdata:/var/lib/postgresql/data"
        ports:
          - 5433:5432  # Debug

    chatdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "chatpgdata:/var/lib/postgresql/data"
        ports:
          - 5434:5432  # Debug
    
    recommenddb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "recommendpgdata:/var/lib/postgresql/data"
        ports:
            - 5435:5432  # debug

volumes: 
    userpgdata:
        driver: "local"
    projectpgdata:
        driver: "local"
    chatpgdata:
        driver: "local"
    recommendpgdata:
        driver: "local"
