version: "3"
services:
    userapi:
        build: userapi
        links:
            - userdb
        depends_on:
            - userdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
        volumes:
            - usericonmedia:/usericon
    
    projectapi:
        build: projectapi
        links:
            - projectdb
        depends_on:
            - projectdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
        volumes:
            - projectimagemedia:/projectimage
    
    chatapi:
        build: chatapi
        links:
            - chatdb
        depends_on:
            - chatdb
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"

    recommendapi:
        build: recommendapi
        links:
            - userapi
            - projectapi
            - recommendcache
        depends_on:
            - recommendcache

    recommendcache:
        image: redis
        volumes:
            - recommendcachedata

    caddy:
        build: .
        volumes:
            - "./Caddyfile:/etc/caddy/Caddyfile"
        links:
            - userapi
        environment: 
            TZ: "UTC"
            HOSTNAME: "projshare.com"
        depends_on:
            - userapi
        ports:
            - 80:80
            - 443:443

    userdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "userpgdata:/var/lib/postgresql/data"
    
    projectdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "projectpgdata:/var/lib/postgresql/data"
    
    chatdb:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "chatpgdata:/var/lib/postgresql/data"


volumes: 
    userpgdata:
        driver: "local"
    usericonmedia:
        driver: "local"
    projectpgdata:
        driver: "local"
    projectimagemedia:
        driver: "local"
    chatpgdata:
        driver: "local"
    recommendcachedata:
        driver: "local"
