version: "3"
services:
    front:
        build: front/project-sharing-page

    userapi:
        build: userapi
        links:
            - db
        depends_on:
            - db
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"
            DB_ECHO: "False"
    
    caddy:
        image: caddy
        volumes:
            - "./Caddyfile:/etc/caddy/Caddyfile"
        links:
            - userapi
            - front
        environment: 
            TZ: "UTC"
            HOSTNAME: "localhost"
        depends_on:
            - userapi
            - front
        ports:
            - 80:80
            - 443:443

    db:
        image: postgres
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg_password"  # WARNING: 運用するときにはパスワードを変える・隠す
        volumes:
            - "pgdata:/var/lib/postgresql/data"

        
volumes: 
    pgdata:
        driver: "local"
